apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "walrus-node.fullname" . }}
  labels:
    {{- include "walrus-node.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "walrus-node.fullname" . }}
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "walrus-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        0.prometheus.io/scrape: "true"
        0.prometheus.io/port: "9184"
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "walrus-node.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "walrus-node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: walrus-node
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /bin/sh
          - -c
          args:
          - |
            mkdir -p /etc/walrus/config
            cp -r -L /opt/walrus/config/* /etc/walrus/config
            exec /opt/walrus/bin/walrus-node run --config-path /etc/walrus/config/walrus-node.yaml
          ports:
            - name: rpc
              containerPort: 9185
              protocol: TCP
            - name: metrics
              containerPort: 9184
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/walrus/db
            - name: config
              mountPath: /opt/walrus/config
              readOnly: true
            {{- if eq .Values.walrus.config.tls.disable_tls false }}
            - name: tls
              mountPath: /opt/walrus/config/tls
              readOnly: true
            {{- end}}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "walrus-node.fullname" . }}
        {{- if eq .Values.walrus.config.tls.disable_tls false }}
        - name: tls
          secret:
            secretName: {{ include "walrus-node.fullname" . }}-tls
        {{- end}}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      storageClassName: {{ .Values.persistence.storageClassName }}
