{{- if .Values.publisher.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "walrus-node.fullname" . }}-publisher
  labels:
    {{- include "walrus-node.labels" . | nindent 4 }}
    role: publisher
spec:
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "walrus-node.selectorLabels" . | nindent 6 }}
      role: publisher
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "walrus-node.selectorLabels" . | nindent 8 }}
        role: publisher
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "walrus-node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: walrus-publisher
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /bin/sh
          - -c
          args:
          - |
            mkdir -p /etc/walrus/config
            cp -r -L /opt/walrus/config/* /etc/walrus/config
            exec /opt/walrus/bin/walrus --config /etc/walrus/config/client_config.yaml publisher --bind-address 0.0.0.0:{{ .Values.publisher.public_port }} --metrics-address 127.0.0.1:{{ .Values.publisher.metrics_port }} --sub-wallets-dir /opt/walrus/wallets --jwt-decode-secret {{ .Values.publisher.decodeSecret }}  --jwt-expiring-sec {{ .Values.publisher.expiringSec }}
          ports:
            - name: rpc
              containerPort: {{ .Values.publisher.public_port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.publisher.metrics_port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /opt/walrus/config
              readOnly: true
            - name: config
              mountPath: /opt/walrus/wallets/sui_client.yaml
              subPath: publisher_sui_client.yaml
              readOnly: true
            - name: config
              mountPath: /opt/walrus/wallets/sui.keystore
              subPath: publisher_sui.keystore
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: {{ include "walrus-node.fullname" . }}
{{- end }}
