{{- if .Values.components.node.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "walrus-node.fullname" . }}
  labels:
    {{- include "walrus-node.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.walrus.config.public_port }}
      targetPort: rpc
      protocol: TCP
      name: walrus
  selector:
    {{- include "walrus-node.selectorLabels" . | nindent 4 }}
    role: node
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "walrus-node.fullname" . }}-metrics
  labels:
    {{- include "walrus-node.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 9184
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "walrus-node.selectorLabels" . | nindent 4 }}
    role: node
{{- end }}
